language: ruby

rvm:
 - 2.7.0

services:
  postgresql

cache: bundler

before_install:
- gem update —system
- gem install bundler

script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec